import type {
  Campaign, Customer, BusinessProfile, RedemptionQueueItem,
} from './types'

export const business: BusinessProfile = {
  id: 'biz-1',
  name: 'Brew & Bite Café',
  category: 'Café & Bakery',
  tagline: 'Your daily dose of happiness ☕',
  description: 'A cozy neighbourhood café serving artisan coffee, fresh bakes, and good vibes since 2019.',
  logo: '☕',
  address: '12, Koramangala 4th Block',
  city: 'Bangalore',
  phone: '+91 98765 43210',
  email: 'hello@brewandbite.in',
  hours: 'Mon–Sun: 7:30 AM – 10:00 PM',
  website: 'brewandbite.in',
  qrCode: 'QR_BREW_BITE_001',
}

export const campaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Weekend Spin Fiesta',
    mechanic: 'spin',
    status: 'active',
    startDate: '2026-06-10',
    endDate: '2026-06-30',
    userCap: 500,
    currentUsers: 312,
    playsPerUser: 1,
    participations: 312,
    rewardsClaimed: 198,
    pin: '472',
    pinExpiresAt: Date.now() + 42000,
    createdAt: '2026-06-09T10:00:00Z',
    rewards: [
      { id: 'r1', name: 'Free Coffee', description: 'Any regular coffee', value: '₹120', icon: '☕' },
      { id: 'r2', name: '20% Off', description: 'On your next bill', value: '20%', icon: '🏷️' },
      { id: 'r3', name: 'Free Muffin', description: 'Any flavour', value: '₹80', icon: '🧁' },
    ],
    config: {
      type: 'spin',
      spinsPerUser: 1,
      segments: [
        { label: 'Free Coffee', reward: 'Free Coffee', probability: 0.15, color: '#7C3AED', isWin: true },
        { label: 'Try Again', reward: null, probability: 0.2, color: '#2A2660', isWin: false },
        { label: '20% Off', reward: '20% Off', probability: 0.2, color: '#EC4899', isWin: true },
        { label: 'Free Muffin', reward: 'Free Muffin', probability: 0.1, color: '#F59E0B', isWin: true },
        { label: 'Better Luck', reward: null, probability: 0.2, color: '#1A1840', isWin: false },
        { label: '₹50 Off', reward: '₹50 Off', probability: 0.15, color: '#06B6D4', isWin: true },
      ],
    },
  },
  {
    id: 'camp-2',
    name: 'Loyalty Stamp Card — June',
    mechanic: 'stamp',
    status: 'active',
    startDate: '2026-06-01',
    endDate: '2026-06-30',
    userCap: 300,
    currentUsers: 187,
    playsPerUser: 10,
    participations: 187,
    rewardsClaimed: 43,
    pin: '815',
    pinExpiresAt: Date.now() + 28000,
    createdAt: '2026-05-30T09:00:00Z',
    rewards: [
      { id: 'r4', name: 'Surprise Drop', description: 'Random reward between stamps 4–6', value: 'Surprise', icon: '🎁' },
      { id: 'r5', name: 'Free Breakfast', description: 'Full breakfast combo for two', value: '₹450', icon: '🍳' },
    ],
    config: {
      type: 'stamp',
      totalStamps: 10,
      surpriseDropRange: [4, 6],
      bigRewardPosition: 10,
      surpriseReward: { id: 'r4', name: 'Surprise Drop', description: 'Random reward', value: 'Surprise', icon: '🎁' },
      bigReward: { id: 'r5', name: 'Free Breakfast', description: 'Full breakfast combo for two', value: '₹450', icon: '🍳' },
    },
  },
  {
    id: 'camp-3',
    name: 'Monsoon Shake & Win',
    mechanic: 'shake',
    status: 'active',
    startDate: '2026-06-13',
    endDate: '2026-07-15',
    userCap: 1000,
    currentUsers: 89,
    playsPerUser: 2,
    participations: 89,
    rewardsClaimed: 61,
    pin: '237',
    pinExpiresAt: Date.now() + 55000,
    createdAt: '2026-06-12T14:00:00Z',
    rewards: [
      { id: 'r6', name: '₹30 Off', description: 'On any beverage', value: '₹30', icon: '🎉' },
      { id: 'r7', name: 'Free Sandwich', description: 'Any sandwich from the menu', value: '₹180', icon: '🥪' },
    ],
    config: {
      type: 'shake',
      playsPerUser: 2,
      rewardType: 'range',
      winProbability: 0.65,
    },
  },
  {
    id: 'camp-4',
    name: 'Lucky Dice — Draft',
    mechanic: 'dice',
    status: 'draft',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    userCap: 400,
    currentUsers: 0,
    playsPerUser: 1,
    participations: 0,
    rewardsClaimed: 0,
    pin: '---',
    pinExpiresAt: 0,
    createdAt: '2026-06-13T08:00:00Z',
    rewards: [
      { id: 'r8', name: 'Free Dessert', description: 'Any dessert from the menu', value: '₹150', icon: '🍰' },
    ],
    config: {
      type: 'dice',
      rollsPerUser: 1,
      outcomes: [
        { value: 1, reward: null, isWin: false },
        { value: 2, reward: null, isWin: false },
        { value: 3, reward: 'Free Dessert', isWin: true },
        { value: 4, reward: '₹50 Off', isWin: true },
        { value: 5, reward: null, isWin: false },
        { value: 6, reward: 'Free Dessert', isWin: true },
      ],
    },
  },
  {
    id: 'camp-5',
    name: 'Summer Lottery Blast',
    mechanic: 'lottery',
    status: 'ended',
    startDate: '2026-05-01',
    endDate: '2026-05-31',
    userCap: 800,
    currentUsers: 800,
    playsPerUser: 1,
    participations: 800,
    rewardsClaimed: 512,
    pin: '---',
    pinExpiresAt: 0,
    createdAt: '2026-04-28T10:00:00Z',
    rewards: [
      { id: 'r9', name: 'Free Month Subscription', description: 'Unlimited coffee for a month', value: '₹1500', icon: '👑' },
    ],
    config: {
      type: 'lottery',
      ticketLimit: 800,
      jackpotReward: { id: 'r9', name: 'Free Month Sub', description: 'Unlimited coffee for a month', value: '₹1500', icon: '👑' },
      tiers: [
        { name: 'Jackpot', reward: 'Free Month Subscription', probability: 0.01, color: '#F5C518' },
        { name: 'Gold', reward: 'Free Breakfast Combo', probability: 0.05, color: '#F59E0B' },
        { name: 'Silver', reward: 'Free Coffee', probability: 0.2, color: '#9B93C8' },
        { name: 'Bronze', reward: '₹30 Off', probability: 0.35, color: '#CD7F32' },
      ],
    },
  },
]

export const customers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Priya Sharma',
    phone: '+91 98765 11111',
    email: 'priya.sharma@gmail.com',
    dob: '1995-03-15',
    joinedAt: '2026-03-10T09:00:00Z',
    lastVisit: '2026-06-12T14:30:00Z',
    totalVisits: 23,
    gamesPlayed: 18,
    rewardsEarned: 12,
    status: 'active',
    rewards: [
      { id: 'cr1', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin', reward: 'Free Coffee', earnedAt: '2026-06-12T14:30:00Z', status: 'redeemed', redeemedAt: '2026-06-12T14:45:00Z', code: 'PRIYA-SF-001' },
      { id: 'cr2', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake', reward: '₹30 Off', earnedAt: '2026-06-13T11:00:00Z', status: 'pending', code: 'PRIYA-SW-002' },
    ],
    gameHistory: [
      { id: 'gh1', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin', playedAt: '2026-06-12T14:30:00Z', won: true, reward: 'Free Coffee' },
      { id: 'gh2', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake', playedAt: '2026-06-13T11:00:00Z', won: true, reward: '₹30 Off' },
    ],
  },
  {
    id: 'cust-2',
    name: 'Arjun Mehta',
    phone: '+91 98765 22222',
    email: 'arjun.mehta@gmail.com',
    dob: '1992-07-22',
    joinedAt: '2026-01-15T10:00:00Z',
    lastVisit: '2026-06-13T09:15:00Z',
    totalVisits: 45,
    gamesPlayed: 38,
    rewardsEarned: 21,
    status: 'active',
    rewards: [
      { id: 'cr3', campaignId: 'camp-2', campaignName: 'Loyalty Stamp Card', mechanic: 'stamp', reward: 'Free Breakfast', earnedAt: '2026-06-10T09:30:00Z', status: 'pending', code: 'ARJUN-SC-003' },
    ],
    gameHistory: [
      { id: 'gh3', campaignId: 'camp-2', campaignName: 'Loyalty Stamp Card', mechanic: 'stamp', playedAt: '2026-06-10T09:30:00Z', won: true, reward: 'Free Breakfast' },
      { id: 'gh4', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin', playedAt: '2026-06-08T15:00:00Z', won: false },
    ],
  },
  {
    id: 'cust-3',
    name: 'Kavya Reddy',
    phone: '+91 98765 33333',
    email: 'kavya.reddy@gmail.com',
    dob: '1998-11-05',
    joinedAt: '2026-04-20T11:00:00Z',
    lastVisit: '2026-06-11T16:45:00Z',
    totalVisits: 12,
    gamesPlayed: 9,
    rewardsEarned: 5,
    status: 'active',
    rewards: [
      { id: 'cr4', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake', reward: 'Free Sandwich', earnedAt: '2026-06-11T16:45:00Z', status: 'pending', code: 'KAVYA-SW-004' },
    ],
    gameHistory: [
      { id: 'gh5', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake', playedAt: '2026-06-11T16:45:00Z', won: true, reward: 'Free Sandwich' },
    ],
  },
  {
    id: 'cust-4',
    name: 'Rohit Nair',
    phone: '+91 98765 44444',
    email: 'rohit.nair@gmail.com',
    dob: '1990-04-30',
    joinedAt: '2026-02-08T08:30:00Z',
    lastVisit: '2026-06-09T10:00:00Z',
    totalVisits: 31,
    gamesPlayed: 25,
    rewardsEarned: 14,
    status: 'active',
    rewards: [],
    gameHistory: [
      { id: 'gh6', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin', playedAt: '2026-06-09T10:00:00Z', won: false },
    ],
  },
  {
    id: 'cust-5',
    name: 'Sneha Iyer',
    phone: '+91 98765 55555',
    email: 'sneha.iyer@gmail.com',
    dob: '1996-08-19',
    joinedAt: '2026-05-01T12:00:00Z',
    lastVisit: '2026-06-07T13:30:00Z',
    totalVisits: 8,
    gamesPlayed: 6,
    rewardsEarned: 3,
    status: 'inactive',
    rewards: [],
    gameHistory: [],
  },
]

export const redemptionQueue: RedemptionQueueItem[] = [
  {
    id: 'rq-1',
    customerId: 'cust-2',
    customerName: 'Arjun Mehta',
    phone: '+91 98765 22222',
    reward: 'Free Breakfast Combo',
    campaignName: 'Loyalty Stamp Card — June',
    mechanic: 'stamp',
    earnedAt: new Date(Date.now() - 180000).toISOString(),
    code: 'ARJUN-SC-003',
  },
  {
    id: 'rq-2',
    customerId: 'cust-3',
    customerName: 'Kavya Reddy',
    phone: '+91 98765 33333',
    reward: 'Free Sandwich',
    campaignName: 'Monsoon Shake & Win',
    mechanic: 'shake',
    earnedAt: new Date(Date.now() - 420000).toISOString(),
    code: 'KAVYA-SW-004',
  },
]
