import type {
  Campaign, Customer, BusinessProfile, RedemptionQueueItem, CustomerBusiness,
} from './types'

export const business: BusinessProfile = {
  id: 'biz-1',
  name: 'Brew & Bite Café',
  category: 'Café & Bakery',
  tagline: 'Your daily dose of happiness ☕',
  description: 'A cozy neighbourhood café serving artisan coffee, fresh bakes, and good vibes since 2019.',
  logo: '☕',
  address: '12, Koramangala 4th Block',
  city: 'Bangalore',
  phone: '+91 98765 43210',
  email: 'hello@brewandbite.in',
  hours: 'Mon–Sun: 7:30 AM – 10:00 PM',
  website: 'brewandbite.in',
  qrCode: 'QR_BREW_BITE_001',
}

export const campaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Weekend Spin Fiesta',
    mechanic: 'spin',
    status: 'active',
    startDate: '2026-06-10',
    endDate: '2026-06-30',
    userCap: 500,
    currentUsers: 312,
    playsPerUser: 1,
    participations: 312,
    rewardsClaimed: 198,
    redeemedCount: 141,
    pin: '472',
    pinExpiresAt: Date.now() + 42000,
    createdAt: '2026-06-09T10:00:00Z',
    rewards: [
      { id: 'r1', name: 'Free Coffee', description: 'Any regular coffee', value: '₹120', icon: '☕' },
      { id: 'r2', name: '20% Off', description: 'On your next bill', value: '20%', icon: '🏷️' },
      { id: 'r3', name: 'Free Muffin', description: 'Any flavour', value: '₹80', icon: '🧁' },
    ],
    config: {
      type: 'spin',
      spinsPerUser: 1,
      segments: [
        { label: 'Free Coffee', reward: 'Free Coffee', probability: 0.15, color: '#7C3AED', isWin: true },
        { label: 'Try Again', reward: null, probability: 0.2, color: '#2A2660', isWin: false },
        { label: '20% Off', reward: '20% Off', probability: 0.2, color: '#EC4899', isWin: true },
        { label: 'Free Muffin', reward: 'Free Muffin', probability: 0.1, color: '#F59E0B', isWin: true },
        { label: 'Better Luck', reward: null, probability: 0.2, color: '#1A1840', isWin: false },
        { label: '₹50 Off', reward: '₹50 Off', probability: 0.15, color: '#06B6D4', isWin: true },
      ],
    },
  },
  {
    id: 'camp-2',
    name: 'Loyalty Stamp Card — June',
    mechanic: 'stamp',
    status: 'active',
    startDate: '2026-06-01',
    endDate: '2026-06-30',
    userCap: 300,
    currentUsers: 187,
    playsPerUser: 10,
    participations: 187,
    rewardsClaimed: 43,
    redeemedCount: 18,
    pin: '815',
    pinExpiresAt: Date.now() + 28000,
    createdAt: '2026-05-30T09:00:00Z',
    rewards: [
      { id: 'r4', name: 'Surprise Drop', description: 'Random reward between stamps 4–6', value: 'Surprise', icon: '🎁' },
      { id: 'r5', name: 'Free Breakfast', description: 'Full breakfast combo for two', value: '₹450', icon: '🍳' },
    ],
    config: {
      type: 'stamp',
      totalStamps: 10,
      surpriseDropRange: [4, 6],
      bigRewardPosition: 10,
      surpriseReward: { id: 'r4', name: 'Surprise Drop', description: 'Random reward', value: 'Surprise', icon: '🎁' },
      bigReward: { id: 'r5', name: 'Free Breakfast', description: 'Full breakfast combo for two', value: '₹450', icon: '🍳' },
    },
  },
  {
    id: 'camp-3',
    name: 'Monsoon Shake & Win',
    mechanic: 'shake',
    status: 'active',
    startDate: '2026-06-13',
    endDate: '2026-07-15',
    userCap: 1000,
    currentUsers: 89,
    playsPerUser: 2,
    participations: 89,
    rewardsClaimed: 61,
    redeemedCount: 28,
    pin: '237',
    pinExpiresAt: Date.now() + 55000,
    createdAt: '2026-06-12T14:00:00Z',
    rewards: [
      { id: 'r6', name: '₹30 Off', description: 'On any beverage', value: '₹30', icon: '🎉' },
      { id: 'r7', name: 'Free Sandwich', description: 'Any sandwich from the menu', value: '₹180', icon: '🥪' },
    ],
    config: {
      type: 'shake',
      playsPerUser: 2,
      rewardType: 'range',
      winProbability: 0.65,
    },
  },
  {
    id: 'camp-4',
    name: 'Lucky Dice — Draft',
    mechanic: 'dice',
    status: 'draft',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    userCap: 400,
    currentUsers: 0,
    playsPerUser: 1,
    participations: 0,
    rewardsClaimed: 0,
    redeemedCount: 0,
    pin: '---',
    pinExpiresAt: 0,
    createdAt: '2026-06-13T08:00:00Z',
    rewards: [
      { id: 'r8', name: 'Free Dessert', description: 'Any dessert from the menu', value: '₹150', icon: '🍰' },
    ],
    config: {
      type: 'dice',
      rollsPerUser: 1,
      outcomes: [
        { value: 1, reward: null, isWin: false },
        { value: 2, reward: null, isWin: false },
        { value: 3, reward: 'Free Dessert', isWin: true },
        { value: 4, reward: '₹50 Off', isWin: true },
        { value: 5, reward: null, isWin: false },
        { value: 6, reward: 'Free Dessert', isWin: true },
      ],
    },
  },
  {
    id: 'camp-5',
    name: 'Summer Lottery Blast',
    mechanic: 'lottery',
    status: 'ended',
    startDate: '2026-05-01',
    endDate: '2026-05-31',
    userCap: 800,
    currentUsers: 800,
    playsPerUser: 1,
    participations: 800,
    rewardsClaimed: 512,
    redeemedCount: 420,
    pin: '---',
    pinExpiresAt: 0,
    createdAt: '2026-04-28T10:00:00Z',
    rewards: [
      { id: 'r9', name: 'Free Month Subscription', description: 'Unlimited coffee for a month', value: '₹1500', icon: '👑' },
    ],
    config: {
      type: 'lottery',
      ticketLimit: 800,
      jackpotReward: { id: 'r9', name: 'Free Month Sub', description: 'Unlimited coffee for a month', value: '₹1500', icon: '👑' },
      tiers: [
        { name: 'Jackpot', reward: 'Free Month Subscription', probability: 0.01, color: '#F5C518' },
        { name: 'Gold', reward: 'Free Breakfast Combo', probability: 0.05, color: '#F59E0B' },
        { name: 'Silver', reward: 'Free Coffee', probability: 0.2, color: '#9B93C8' },
        { name: 'Bronze', reward: '₹30 Off', probability: 0.35, color: '#CD7F32' },
      ],
    },
  },
  {
    id: 'camp-6',
    name: 'Daily Check-in Rewards',
    mechanic: 'checkin',
    status: 'active',
    startDate: '2026-06-01',
    endDate: '2026-08-31',
    userCap: 2000,
    currentUsers: 1247,
    playsPerUser: 1,
    participations: 3421,
    rewardsClaimed: 3421,
    redeemedCount: 1854,
    pin: '123',
    pinExpiresAt: Date.now() + 3600000,
    createdAt: '2026-05-31T10:00:00Z',
    rewards: [
      { id: 'r10', name: '100 Points', description: 'Loyalty points for daily check-in', value: '100pts', icon: '📍' },
    ],
    config: {
      type: 'checkin',
      pointsPerCheckIn: 100,
      maxCheckInsPerDay: 1,
      checkInsPerUser: 30,
    },
  },
]

export const customers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Priya Sharma',
    phone: '+91 98765 11111',
    email: 'priya.sharma@gmail.com',
    dob: '1995-03-15',
    joinedAt: '2026-03-10T09:00:00Z',
    lastVisit: '2026-06-12T14:30:00Z',
    totalVisits: 23,
    gamesPlayed: 18,
    rewardsEarned: 12,
    status: 'active',
    rewards: [
      // ── Active (pending) rewards ───────────────────────────────
      {
        id: 'cr-shake-amber', campaignId: 'camp-3', campaignName: 'Scratch & Win',
        mechanic: 'shake', reward: '₹30 Off Your Next Bill',
        earnedAt: '2026-06-13T11:00:00Z', expiresAt: '2026-06-18T23:59:59Z',
        status: 'pending', code: 'PRIYA-SW-002',
        businessId: 'biz-amber', businessName: 'Amber Cafe', businessEmoji: '☕',
        businessCoverFrom: '#92400E', businessCoverTo: '#78350F',
      },
      {
        id: 'cr-spin-verde', campaignId: 'camp-verde-spin', campaignName: 'Spin the Wheel',
        mechanic: 'spin', reward: 'Free Dessert 🍮',
        earnedAt: '2026-06-14T19:30:00Z', expiresAt: '2026-06-21T23:59:59Z',
        status: 'pending', code: 'PRIYA-VB-021',
        businessId: 'biz-verde', businessName: 'Verde Bistro', businessEmoji: '🍝',
        businessCoverFrom: '#14532D', businessCoverTo: '#065F46',
      },
      {
        id: 'cr-stamp-noir', campaignId: 'camp-noir-stamp', campaignName: 'Stamp Card',
        mechanic: 'stamp', reward: 'Free Deep Conditioning Treatment',
        earnedAt: '2026-06-10T13:00:00Z', expiresAt: '2026-06-28T23:59:59Z',
        status: 'pending', code: 'PRIYA-NS-007',
        businessId: 'biz-noir', businessName: 'Noir Hair Studio', businessEmoji: '✂️',
        businessCoverFrom: '#1C1917', businessCoverTo: '#44403C',
      },
      {
        id: 'cr-dice-lustre', campaignId: 'camp-lustre-dice', campaignName: 'Mystery Box',
        mechanic: 'dice', reward: '₹500 Off on Next Purchase',
        earnedAt: '2026-06-11T16:00:00Z', expiresAt: '2026-06-30T23:59:59Z',
        status: 'pending', code: 'PRIYA-LJ-013',
        businessId: 'biz-lustre', businessName: 'Lustre Jewellers', businessEmoji: '💎',
        businessCoverFrom: '#7C2D12', businessCoverTo: '#B45309',
      },
      {
        id: 'cr-shake-noir', campaignId: 'camp-noir-shake', campaignName: 'Scratch Card',
        mechanic: 'shake', reward: '₹200 Off Any Service',
        earnedAt: '2026-06-09T12:30:00Z', expiresAt: '2026-07-09T23:59:59Z',
        status: 'pending', code: 'PRIYA-NS-009',
        businessId: 'biz-noir', businessName: 'Noir Hair Studio', businessEmoji: '✂️',
        businessCoverFrom: '#1C1917', businessCoverTo: '#44403C',
      },
      {
        id: 'cr-checkin-ironforge', campaignId: 'camp-ig-checkin', campaignName: 'Daily Check-in',
        mechanic: 'checkin', reward: 'Free Protein Shake 🥤',
        earnedAt: '2026-06-08T07:00:00Z', expiresAt: '2026-07-08T23:59:59Z',
        status: 'pending', code: 'PRIYA-IF-042',
        businessId: 'biz-ironforge', businessName: 'Iron Forge', businessEmoji: '🏋️',
        businessCoverFrom: '#111827', businessCoverTo: '#374151',
      },
      // ── Redeemed (history) ─────────────────────────────────────
      {
        id: 'cr1', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta',
        mechanic: 'spin', reward: 'Free Coffee ☕',
        earnedAt: '2026-06-12T14:30:00Z', expiresAt: '2026-06-19T23:59:59Z',
        status: 'redeemed', redeemedAt: '2026-06-12T14:45:00Z', code: 'PRIYA-SF-001',
        businessId: 'biz-amber', businessName: 'Amber Cafe', businessEmoji: '☕',
        businessCoverFrom: '#92400E', businessCoverTo: '#78350F',
      },
      {
        id: 'cr-dice-glam', campaignId: 'camp-glam-dice', campaignName: 'Mystery Box',
        mechanic: 'dice', reward: 'Free Face Mask Session 🧖',
        earnedAt: '2026-06-05T15:00:00Z', expiresAt: '2026-06-20T23:59:59Z',
        status: 'redeemed', redeemedAt: '2026-06-07T11:00:00Z', code: 'PRIYA-GS-005',
        businessId: 'biz-glamspa', businessName: 'Glam Spa', businessEmoji: '💆',
        businessCoverFrom: '#4A044E', businessCoverTo: '#701A75',
      },
      {
        id: 'cr-stamp-amber-old', campaignId: 'camp-amber-stamp', campaignName: 'Stamp Card',
        mechanic: 'stamp', reward: 'Free Croissant 🥐',
        earnedAt: '2026-05-28T09:00:00Z', expiresAt: '2026-06-28T23:59:59Z',
        status: 'redeemed', redeemedAt: '2026-06-01T08:30:00Z', code: 'PRIYA-AM-003',
        businessId: 'biz-amber', businessName: 'Amber Cafe', businessEmoji: '☕',
        businessCoverFrom: '#92400E', businessCoverTo: '#78350F',
      },
    ],
    gameHistory: [
      { id: 'gh1', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin', playedAt: '2026-06-12T14:30:00Z', won: true, reward: 'Free Coffee' },
      { id: 'gh2', campaignId: 'camp-3', campaignName: 'Scratch & Win', mechanic: 'shake', playedAt: '2026-06-13T11:00:00Z', won: true, reward: '₹30 Off' },
    ],
  },
  {
    id: 'cust-2',
    name: 'Arjun Mehta',
    phone: '+91 98765 22222',
    email: 'arjun.mehta@gmail.com',
    dob: '1992-07-22',
    joinedAt: '2026-01-15T10:00:00Z',
    lastVisit: '2026-06-13T09:15:00Z',
    totalVisits: 45,
    gamesPlayed: 38,
    rewardsEarned: 21,
    status: 'active',
    rewards: [
      { id: 'cr3', campaignId: 'camp-2', campaignName: 'Loyalty Stamp Card', mechanic: 'stamp', reward: 'Free Breakfast', earnedAt: '2026-06-10T09:30:00Z', status: 'pending', code: 'ARJUN-SC-003' },
    ],
    gameHistory: [
      { id: 'gh3', campaignId: 'camp-2', campaignName: 'Loyalty Stamp Card', mechanic: 'stamp', playedAt: '2026-06-10T09:30:00Z', won: true, reward: 'Free Breakfast' },
      { id: 'gh4', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin', playedAt: '2026-06-08T15:00:00Z', won: false },
    ],
  },
  {
    id: 'cust-3',
    name: 'Kavya Reddy',
    phone: '+91 98765 33333',
    email: 'kavya.reddy@gmail.com',
    dob: '1998-11-05',
    joinedAt: '2026-04-20T11:00:00Z',
    lastVisit: '2026-06-11T16:45:00Z',
    totalVisits: 12,
    gamesPlayed: 9,
    rewardsEarned: 5,
    status: 'active',
    rewards: [
      { id: 'cr4', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake', reward: 'Free Sandwich', earnedAt: '2026-06-11T16:45:00Z', status: 'pending', code: 'KAVYA-SW-004' },
    ],
    gameHistory: [
      { id: 'gh5', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake', playedAt: '2026-06-11T16:45:00Z', won: true, reward: 'Free Sandwich' },
    ],
  },
  {
    id: 'cust-4',
    name: 'Rohit Nair',
    phone: '+91 98765 44444',
    email: 'rohit.nair@gmail.com',
    dob: '1990-04-30',
    joinedAt: '2026-02-08T08:30:00Z',
    lastVisit: '2026-06-09T10:00:00Z',
    totalVisits: 31,
    gamesPlayed: 25,
    rewardsEarned: 14,
    status: 'active',
    rewards: [],
    gameHistory: [
      { id: 'gh6', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin', playedAt: '2026-06-09T10:00:00Z', won: false },
    ],
  },
  {
    id: 'cust-5',
    name: 'Sneha Iyer',
    phone: '+91 98765 55555',
    email: 'sneha.iyer@gmail.com',
    dob: '1996-08-19',
    joinedAt: '2026-05-01T12:00:00Z',
    lastVisit: '2026-06-07T13:30:00Z',
    totalVisits: 8,
    gamesPlayed: 6,
    rewardsEarned: 3,
    status: 'inactive',
    rewards: [],
    gameHistory: [],
  },
  {
    id: 'cust-6',
    name: 'Farhan Siddiqui',
    phone: '+91 98765 66666',
    email: 'farhan.siddiqui@gmail.com',
    dob: '1991-12-03',
    joinedAt: '2026-01-20T10:00:00Z',
    lastVisit: '2026-05-09T11:00:00Z',
    totalVisits: 18,
    gamesPlayed: 14,
    rewardsEarned: 7,
    status: 'active',
    rewards: [
      { id: 'cr7', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake' as const, reward: '₹50 Off', earnedAt: '2026-05-09T11:00:00Z', status: 'pending' as const, code: 'FARHAN-SW-007' },
    ],
    gameHistory: [
      { id: 'gh9', campaignId: 'camp-3', campaignName: 'Monsoon Shake & Win', mechanic: 'shake' as const, playedAt: '2026-05-09T11:00:00Z', won: true, reward: '₹50 Off' },
      { id: 'gh10', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin' as const, playedAt: '2026-04-28T13:00:00Z', won: false },
    ],
  },
  {
    id: 'cust-7',
    name: 'Divya Krishnan',
    phone: '+91 98765 77777',
    email: 'divya.krishnan@gmail.com',
    dob: '1997-06-25',
    joinedAt: '2026-02-14T09:00:00Z',
    lastVisit: '2026-04-14T15:30:00Z',
    totalVisits: 5,
    gamesPlayed: 4,
    rewardsEarned: 1,
    status: 'inactive',
    rewards: [],
    gameHistory: [
      { id: 'gh11', campaignId: 'camp-1', campaignName: 'Weekend Spin Fiesta', mechanic: 'spin' as const, playedAt: '2026-04-14T15:30:00Z', won: false },
    ],
  },
]

export const customerBusinesses: CustomerBusiness[] = [
  { id: 'biz-amber', name: 'Amber Cafe', category: 'Cafe', tagline: 'Slow roasts. Honeyed pastries. A regulars-only kind of warm.', rating: 4.7, reviews: 312, distance: '0.4 km', location: 'Indiranagar, Bangalore', phone: '+91 80 4567 8901', openUntil: 'Open until 10 PM', coverImage: 'https://picsum.photos/seed/amber-cafe/800/500', coverFrom: '#92400E', coverTo: '#78350F', coverEmoji: '☕', mechanics: [
    { type: 'stamp',   label: 'Stamp Card',     description: 'Buy 9, get the 10th free. Classic, proven, beloved.',  status: 'active', startDate: '2026-05-01', endDate: '2026-07-31', participants: 198, totalRewards: 45,  activeToday: 23, playedToday: false, stampsCollected: 4,  totalStamps: 10, finalReward: 'Free Breakfast Combo' },
    { type: 'spin',    label: 'Spin the Wheel', description: 'A flick of fortune at every checkout.',                status: 'active', startDate: '2026-06-01', endDate: '2026-06-30', participants: 312, totalRewards: 87,  activeToday: 41, playedToday: true,  prizes: ['Free Coffee ☕', '20% Off 🏷️', 'Free Muffin 🧁', 'Free Espresso ☕'] },
    { type: 'shake',   label: 'Scratch Card',   description: 'Targeted offers, redeemable at the counter.',         status: 'paused', startDate: '2026-04-01', endDate: '2026-06-30', participants: 76,  totalRewards: 22,  activeToday: 0,  playedToday: false, prizes: ['₹50 Off 🏷️', 'Free Pastry 🥐', 'Free Latte ☕'] },
    { type: 'checkin', label: 'Daily Check-in', description: 'Check in every day and earn 100 points per visit.',   status: 'active', startDate: '2026-06-01', endDate: '2026-12-31', participants: 143, totalRewards: 143, activeToday: 67, playedToday: false, checkInStreak: 5, totalPoints: 500 },
  ]},
  { id: 'biz-noir', name: 'Noir Hair Studio', category: 'Salon', tagline: 'Boutique cuts and colour. Quiet luxury for everyday.', rating: 4.9, reviews: 198, distance: '1.1 km', location: 'Koramangala, Bangalore', phone: '+91 80 2345 6789', openUntil: 'Open until 8 PM', coverImage: 'https://picsum.photos/seed/noir-studio/800/500', coverFrom: '#1C1917', coverTo: '#44403C', coverEmoji: '✂️', mechanics: [
    { type: 'stamp',   label: 'Stamp Card',     description: 'Get your 10th service free.',                          status: 'active', startDate: '2026-04-15', endDate: '2026-08-15', participants: 143, totalRewards: 31,  activeToday: 12, playedToday: false, stampsCollected: 7, totalStamps: 10, finalReward: 'Free Styling Session' },
    { type: 'shake',   label: 'Scratch Card',   description: 'Tactile thrill — peel, reveal, smile.',               status: 'active', startDate: '2026-06-01', endDate: '2026-07-15', participants: 89,  totalRewards: 19,  activeToday: 18, playedToday: false, prizes: ['₹200 Off 🏷️', 'Free Hair Wash 🚿', 'Free Deep Condition 💆'] },
    { type: 'dice',    label: 'Mystery Box',    description: 'Curiosity converts. A surprise gift inside every box.',status: 'ended',  startDate: '2026-03-01', endDate: '2026-05-31', participants: 201, totalRewards: 56,  activeToday: 0,  playedToday: false, prizes: ['Free Serum 💧', '₹300 Off 🏷️', 'Free Treatment 💆'] },
    { type: 'checkin', label: 'Daily Check-in', description: 'Check in every day and earn 100 points per visit.',   status: 'active', startDate: '2026-06-01', endDate: '2026-12-31', participants: 98,  totalRewards: 98,  activeToday: 31, playedToday: true,  checkInStreak: 3, totalPoints: 300 },
  ]},
  { id: 'biz-ironforge', name: 'Iron Forge', category: 'Gym', tagline: 'Strength built quiet. No grunts, just gains.', rating: 4.6, reviews: 421, distance: '2.3 km', location: 'HSR Layout, Bangalore', phone: '+91 80 3456 7890', openUntil: 'Open until 11 PM', coverImage: 'https://picsum.photos/seed/iron-forge-gym/800/500', coverFrom: '#111827', coverTo: '#374151', coverEmoji: '🏋️', mechanics: [
    { type: 'stamp',   label: 'Stamp Card',      description: 'Complete 10 sessions, get one free.',                 status: 'active', startDate: '2026-01-01', endDate: '2026-12-31', participants: 512, totalRewards: 98,  activeToday: 54, playedToday: false, stampsCollected: 2, totalStamps: 10, finalReward: 'Free Month Membership' },
    { type: 'lottery', label: 'Monthly Draw',    description: 'Monthly prize draw for consistent members.',          status: 'active', startDate: '2026-06-01', endDate: '2026-06-30', participants: 287, totalRewards: 12,  activeToday: 29, playedToday: false, drawDate: '2026-06-30', userTickets: 3 },
    { type: 'spin',    label: 'Paced Collection', description: 'Spin after every milestone.',                        status: 'draft',  startDate: '2026-07-01', endDate: '2026-09-30', participants: 0,   totalRewards: 0,   activeToday: 0,  playedToday: false, prizes: ['Free PT Session 🏋️', 'Free Protein Shake 🥤', '₹500 Off 🏷️'] },
    { type: 'checkin', label: 'Daily Check-in',  description: 'Check in every day and earn 100 points per visit.',  status: 'active', startDate: '2026-06-01', endDate: '2026-12-31', participants: 267, totalRewards: 267, activeToday: 89, playedToday: false, checkInStreak: 12, totalPoints: 1200 },
  ]},
  { id: 'biz-lustre', name: 'Lustre Jewellers', category: 'Jewellery', tagline: 'Heritage craft. Modern sensibility. An heirloom waiting.', rating: 4.8, reviews: 256, distance: '3.4 km', location: 'Jayanagar, Bangalore', phone: '+91 80 5678 9012', openUntil: 'Open until 9 PM', coverImage: 'https://picsum.photos/seed/lustre-jewel/800/500', coverFrom: '#7C2D12', coverTo: '#B45309', coverEmoji: '💎', mechanics: [
    { type: 'dice',    label: 'Mystery Box',      description: 'Curiosity converts. A surprise gift inside every box.',status: 'active', startDate: '2026-05-15', endDate: '2026-07-15', participants: 167, totalRewards: 38, activeToday: 22, playedToday: false, prizes: ['Silver Bracelet 💍', '₹500 Off 🏷️', 'Free Cleaning 💎'] },
    { type: 'lottery', label: 'Jewellery Draw',  description: 'Win exclusive jewellery pieces.',                     status: 'active', startDate: '2026-06-01', endDate: '2026-06-30', participants: 94,  totalRewards: 5,  activeToday: 14, playedToday: false, drawDate: '2026-06-30', userTickets: 1 },
    { type: 'stamp',   label: 'Paced Collection', description: 'Collect points with every purchase.',                status: 'active', startDate: '2026-03-01', endDate: '2026-08-31', participants: 321, totalRewards: 73, activeToday: 19, playedToday: false, stampsCollected: 6, totalStamps: 10, finalReward: 'Free Silver Pendant' },
    { type: 'checkin', label: 'Daily Check-in',  description: 'Check in every day and earn 100 points per visit.',  status: 'active', startDate: '2026-06-01', endDate: '2026-12-31', participants: 112, totalRewards: 112, activeToday: 28, playedToday: false, checkInStreak: 2, totalPoints: 200 },
  ]},
  { id: 'biz-verde', name: 'Verde Bistro', category: 'Restaurant', tagline: 'Mediterranean small plates. Big-spirited Sunday toasts.', rating: 4.5, reviews: 340, distance: '1.8 km', location: 'Whitefield, Bangalore', phone: '+91 80 6789 0123', openUntil: 'Open until 11 PM', coverImage: 'https://picsum.photos/seed/verde-bistro/800/500', coverFrom: '#14532D', coverTo: '#065F46', coverEmoji: '🍝', mechanics: [
    { type: 'spin',    label: 'Spin the Wheel', description: 'A flick of fortune at every checkout.',         status: 'active', startDate: '2026-06-01', endDate: '2026-06-30', participants: 421, totalRewards: 110, activeToday: 57, playedToday: false, prizes: ['Free Dessert 🍮', '10% Off 🏷️', 'Free Mocktail 🍹', 'Free Starter 🫔'] },
    { type: 'shake',   label: 'Scratch Card',   description: 'Peel, reveal, and redeem at checkout.',        status: 'active', startDate: '2026-05-01', endDate: '2026-07-31', participants: 188, totalRewards: 47,  activeToday: 34, playedToday: true,  prizes: ['₹100 Off 🏷️', 'Free Bread Basket 🥖', 'Free Dessert 🍮'] },
    { type: 'dice',    label: 'Mystery Dish',   description: 'Targeted offers, redeemable at the counter.', status: 'paused', startDate: '2026-04-01', endDate: '2026-06-15', participants: 65,  totalRewards: 18,  activeToday: 0,  playedToday: false, prizes: ['Free Starter 🫔', '₹150 Off 🏷️', 'Chef Special 🍝'] },
    { type: 'checkin', label: 'Daily Check-in', description: 'Check in every day and earn 100 points per visit.', status: 'active', startDate: '2026-06-01', endDate: '2026-12-31', participants: 189, totalRewards: 189, activeToday: 73, playedToday: false, checkInStreak: 7, totalPoints: 700 },
  ]},
  { id: 'biz-glamspa', name: 'Glam Spa', category: 'Salon', tagline: 'Where wellness meets indulgence. Every visit, a ritual.', rating: 4.5, reviews: 340, distance: '1.8 km', location: 'Jayanagar, Bangalore', phone: '+91 80 7890 1234', openUntil: 'Open until 9 PM', coverImage: 'https://picsum.photos/seed/glam-spa-blr/800/500', coverFrom: '#4A044E', coverTo: '#701A75', coverEmoji: '💆', mechanics: [
    { type: 'stamp',   label: 'Stamp Card',     description: 'Buy 9, get the 10th free. Classic, proven, beloved.', status: 'active', startDate: '2026-05-01', endDate: '2026-08-31', participants: 234, totalRewards: 52,  activeToday: 17, playedToday: false, stampsCollected: 1, totalStamps: 10, finalReward: 'Free Spa Session' },
    { type: 'dice',    label: 'Mystery Box',    description: 'Curiosity converts. A surprise gift inside every box.',status: 'active', startDate: '2026-06-01', endDate: '2026-07-31', participants: 119, totalRewards: 29,  activeToday: 21, playedToday: false, prizes: ['Free Face Mask 🧖', '₹200 Off 🏷️', 'Free Aromatherapy 🕯️'] },
    { type: 'spin',    label: 'Spin the Wheel', description: 'A flick of fortune at every spin.',                  status: 'active', startDate: '2026-06-10', endDate: '2026-07-10', participants: 78,  totalRewards: 21,  activeToday: 13, playedToday: false, prizes: ['Free Pedicure 💅', '30% Off 🏷️', 'Free Eye Treatment 👁️'] },
    { type: 'checkin', label: 'Daily Check-in', description: 'Check in every day and earn 100 points per visit.',  status: 'active', startDate: '2026-06-01', endDate: '2026-12-31', participants: 156, totalRewards: 156, activeToday: 43, playedToday: false, checkInStreak: 1, totalPoints: 100 },
  ]},
]

export const redemptionQueue: RedemptionQueueItem[] = [
  {
    id: 'rq-1',
    customerId: 'cust-2',
    customerName: 'Arjun Mehta',
    phone: '+91 98765 22222',
    reward: 'Free Breakfast Combo',
    campaignName: 'Loyalty Stamp Card — June',
    mechanic: 'stamp',
    earnedAt: new Date(Date.now() - 180000).toISOString(),
    code: 'ARJUN-SC-003',
  },
  {
    id: 'rq-2',
    customerId: 'cust-3',
    customerName: 'Kavya Reddy',
    phone: '+91 98765 33333',
    reward: 'Free Sandwich',
    campaignName: 'Monsoon Shake & Win',
    mechanic: 'shake',
    earnedAt: new Date(Date.now() - 420000).toISOString(),
    code: 'KAVYA-SW-004',
  },
]
